name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Hacer checkout del código
      - uses: actions/checkout@v4

      # Paso 2: Cambiar al directorio 'multiplos'
      - run: cd multiplos

      # Paso 3: Instalar dependencias y hacer build
      - run: npm install && npm run build

      # Paso 4: Desplegar en Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_APP_DEVELOPER_A2983 }}
          channelId: live
          projectId: app-developer-a2983
